# Section for airthings wave plus configuration
airthings_wave_plus:
  # Bluetooth configuration
  bluetooth:
    # Bluetooth MAC adress of Airthings Wave Plus
    # Application will scan for device either by Airthings Wave Plus bluetooth MAC address or Airthings Wave Plus serial Number
    mac_address: "58:93:D8:8B:F2:57"
  # 10-digit Airthings Wave Plus serial number: Can be found under the magnetic backplate of your Airthings Wave Plus
  # Application will scan for device either by Airthings Wave Plus bluetooth MAC address or Airthings Wave Plus serial Number
  serial_number: 2930051107

# Sectiom for scheduler configuration
scheduler:
  # Delay in seconds (Keep in mind that Airthings Wave Plus will refresh sensor measurements every 5minutes)
  delay: 150

# Section for configuration of publishers
publishers:
  #Section for publishing to Apache Kafka
  kafka:
    # Is publishing to Kafka enabled [True | False]
    enabled: True
    # Kafka bootstrap servers. Multiple servers can be added separated by comma e.g.: "IP:PORT,IP:PORT,IP:PORT"
    bootstrap_servers: "192.168.1.111:9092,192.168.1.111:9093,192.168.1.111:9094"
    # Topic where message should be published
    topic: "push.measurements.airthings"
    # Security protocol: e.g. SASL_SSL
    security_protocol: SASL_SSL
    # SSL CA cert file path (with extension), e.g.: "./CARoot.pem"
    ssl_ca_cert_file: "./CARoot.pem"
    # SASL Mechanism
    sasl_mechanism: PLAIN
    # SASL Username
    sasl_username: kafkauser
    # SASL Password
    sasl_password: "rj6Ht1S+KmB57Rtz1+2hri9gdQusaa"

  #Section for publishing to MQTT
  mqtt:
    # Is publishing to MQTT enabled [True | False]
    enabled: True
    # MQTT Broker hostname
    hostname: vm-services-1
    # Port used for connection to broker
    port: 8883
    # Connection type: [MQTT | TLS]
    connection_type: TLS
    # Section for TLS related options (For more information check Python Paho Documentation)
    tls:
      # A string path to the Certificate Authority certificate files that are to be treated as trusted by this client. Leave empty or fill None to use default.
      ca_certs: "./CARoot.pem"
      # Strings pointing to the PEM encoded client certificate and private keys respectively. Leave empty or fill None to use default.
      certfile:
      # Strings pointing to the PEM encoded client certificate and private keys respectively. Leave empty or fill None to use default.
      keyfile:
      # Defines the certificate requirements that the client imposes on the broker. Leave empty or fill None to use default.
      cert_req:
      # Specifies the version of the SSL/TLS protocol to be used. Leave empty or fill None to use default.
      tls_version:
      # A string specifying which encryption ciphers are allowable for this connection. Leave empty or fill None to use default.
      ciphers:
    # Username for brokers with authentication
    username: user001
    #Password for brokers with authentication
    password: m97hBnvb567hd4sLsva3vrx9X2
    # Topic where message should be published
    topic: measurements/airthings
    # QOS setting to be used when publishing (default: 0)
    qos: 0
    # Set the message to be retained [True | False]
    retain_msg: True

# Application logging configuration
log:
  console:
    # Log level for console (stdout) logging
    level: INFO
  # Section for file loggers
  file:
    # Logging to .log files
    log:
      # Is .log file logging enabled [True | False]
      enabled: True
      # Log level for .log file logger
      level: DEBUG
    err:
      # Is .err file logging enabled (file logger which only record errors) [True | False]
      enabled: True
